name: Terraform Init

on:
  workflow_dispatch:

jobs:
  terraform-init:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
      TF_VAR_linode_pat: ${{ secrets.LINODE_PAT }}
      TF_VAR_instance_default_root_pass: ${{ secrets.INSTANCE_DEFAULT_ROOT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

      - name: Install Terraform
        run: |
          tfenv install
          tfenv use

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: TFLint Check
        run: |
          tflint --init
          tflint

      - name: Terraform Init
        run: terraform init
