name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - "*.tf"
      - "*.tfvars"
      - ".terraform.lock.hcl"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1
  LINODE_TOKEN: ${{ secrets.LINODE_PAT }}
  TF_VAR_instance_default_root_pass: ${{ secrets.INSTANCE_DEFAULT_ROOT_PASSWORD }}

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: terraform fmt -check

  lint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0
          cache: true
      - run: |
          tflint --init
          tflint

  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: terraform plan

  all-checks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [fmt, lint, validate, plan]
    steps:
      - name: All checks have passed
        run: echo "All checks have passed successfully."
